project:
  type: website

website:
  title: "Adventures in Bioimaging"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
execute:
  freeze: auto

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    header-includes: |
      <script defer data-domain="vangberg.github.io/adventures-in-bioimaging" src="https://plausible.io/js/script.js"></script>

editor: visual

