project:
  type: website

website:
  title: "Adventures in Bioimaging"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
execute:
  freeze: auto

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

